version: "3.9"
services:
  kam:
    image: ghcr.io/thedinz/kam:latest
    container_name: kam
    restart: unless-stopped
    ports:
      - "7171:8000"
    environment:
      KAM_ASSETS_ROOT: /assets
      COLLECTIONS_ROOT: /assets/Collections
      PLEX_VERIFY_SSL: "true"
    volumes:
      - /mnt/user/appdata/kam:/config:rw
      - /mnt/user/media/assets:/assets:rw
