version: "3.9"
services:
  kam:
    image: ghcr.io/thedinz/kam:latest
    container_name: kam
    restart: unless-stopped
    ports:
      - "7171:7171"
    env_file:
      - .env
    volumes:
      - /mnt/user/appdata/kam/assets:/assets:rw
